# Generated by Django 5.2.4 on 2025-08-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimplePredictionHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('consumed_units', models.FloatField()),
                ('predicted_units', models.FloatField()),
                ('model_predictions', models.JSONField(blank=True, null=True)),
                ('appliance_data', models.JSONField(blank=True, null=True)),
                ('slab_wise_bill', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'simple_prediction_history',
                'ordering': ['-timestamp'],
            },
        ),
    ]
