# Streamlit Cloud Secrets Configuration
# SIMPLE: Use only Gemini API key (100% free)

# AI API Keys
# Get your Gemini API key from: https://makersuite.google.com/app/apikey
GEMINI_API_KEY = "AIzaSyBAvR2V2oMsQ7GgQsofonhPXdruGww_gDs"

# Project Directories
PROJECT_DATA_DIR = "./secpars_app/project_data"
CHROMA_DIR = "./secpars_app/chroma_db"

# Other Configuration
DEBUG = "false"
ENVIRONMENT = "production" 