# Streamlit Cloud Secrets Configuration
# Add your actual API keys here

# AI API Keys
GEMINI_API_KEY = "YOUR_GEMINI_KEY_1,YOUR_GEMINI_KEY_2,YOUR_GEMINI_KEY_3"
OPENAI_API_KEY = "IzaSyBgQ1qGe_lNAdHvNc_SVWT7TbCjfFNzbko"

# Project Directories
PROJECT_DATA_DIR = "./secpars_app/project_data"
CHROMA_DIR = "./secpars_app/chroma_db"

# Other Configuration
DEBUG = "false"
ENVIRONMENT = "production" 