# Streamlit Cloud Secrets Configuration
# Add your actual API keys here

# AI API Keys
GEMINI_API_KEY = "your_gemini_api_key_here"
OPENAI_API_KEY = "your_openai_api_key_here"

# Project Directories
PROJECT_DATA_DIR = "./secpars_app/project_data"
CHROMA_DIR = "./secpars_app/chroma_db"

# Other Configuration
DEBUG = "false"
ENVIRONMENT = "production" 