# Streamlit Cloud Secrets Configuration
# FREE SOLUTION: Use only Gemini API (completely free)

# AI API Keys
# Get your Gemini API key from: https://makersuite.google.com/app/apikey
# Gemini is 100% FREE with unlimited usage
GEMINI_API_KEY = "your-gemini-api-key-here"

# OpenAI API Key (Optional - Only if you have free credits)
# Get your OpenAI API key from: https://platform.openai.com/account/api-keys
# OpenAI has $5 free tier monthly limit
OPENAI_API_KEY = "your-openai-api-key-here"

# Project Directories
PROJECT_DATA_DIR = "./secpars_app/project_data"
CHROMA_DIR = "./secpars_app/chroma_db"

# Other Configuration
DEBUG = "false"
ENVIRONMENT = "production" 