# Streamlit Cloud Secrets Configuration
# GEMINI ROTATION KEYS SYSTEM: Multiple keys for unlimited usage

# AI API Keys
# Get multiple Gemini API keys from: https://makersuite.google.com/app/apikey
# Format: key1,key2,key3 (comma separated)
# Each key gets $15 free credit monthly
GEMINI_API_KEYS = "key1,key2,key3"

# Single Gemini key (fallback)
GEMINI_API_KEY = "your-primary-gemini-key-here"

# OpenAI API Key (Optional - Only if you have free credits)
# Get your OpenAI API key from: https://platform.openai.com/account/api-keys
# OpenAI has $5 free tier monthly limit
OPENAI_API_KEY = "your-openai-api-key-here"

# Project Directories
PROJECT_DATA_DIR = "./secpars_app/project_data"
CHROMA_DIR = "./secpars_app/chroma_db"

# Other Configuration
DEBUG = "false"
ENVIRONMENT = "production" 